-- [v26.5] 포인트 트랜잭션(통장) 시스템을 위한 스키마 업데이트
-- Supabase SQL Editor에 복사해서 실행해 주세요! 🫡🐟💰

-- 1. point_transactions 테이블 생성
CREATE TABLE IF NOT EXISTS point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    type TEXT NOT NULL, -- 'RUN', 'MEDAL', 'ATTENDANCE', 'STREAK', 'DAILY_QUEST' 등
    reference_id TEXT NOT NULL, -- 중복 지급 방지를 위한 유니크 키 (예: 'medal:m1', 'record:123')
    description TEXT NOT NULL,
    balance_snapshot INTEGER, -- 해당 시점의 예상 잔액 (선택 사항)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- 동일 유저의 동일 이벤트 중복 지급 방지
    UNIQUE(user_id, reference_id)
);

-- 2. RLS 보안 정책 설정
ALTER TABLE point_transactions ENABLE ROW LEVEL SECURITY;

-- 자신의 트랜잭션만 조회 가능
CREATE POLICY "Users can view their own point transactions" 
ON point_transactions FOR SELECT 
USING (auth.uid() = user_id);

-- 자신의 트랜잭션만 생성 가능
CREATE POLICY "Users can insert their own point transactions" 
ON point_transactions FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 3. 이력이 쌓일 때마다 프로필의 포인트 총점을 업데이트하고 싶은 경우를 대비해 인덱스 최적화
CREATE INDEX IF NOT EXISTS idx_point_transactions_user_id ON point_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_point_transactions_created_at ON point_transactions(created_at DESC);

-- 4. 기존 point_logs 테이블이 있다면 데이터 정합성을 위해 참고용으로 보관하거나 
--    새로운 시스템 안착 후 삭제를 권장합니다.
